### ISSUE TITLE
import produces segmentation fault

### ISSUE THREAD

**Issue by dimitrisl** [InsightSoftwareConsortium/ITKAnisotropicDiffusionLBR#32]
Hello, 
I'm trying to import itk in order to perform de-noising in some pictures, but as soon as i import a module from itk library i get a seg fault.
I installed it with pip and i've also tried to clone and install it with the setup.py file. My python setup is 3.6 in an isolated virtualenv. Are there any other prequisites i need to install (i've already checked the documentation) ? I've also tried to install the dockerised version with no success whatsoever. 
I would really appreciate if you could help me.
Regards
--Dimitris

**Comment by thewtex** [comment]
Hello Dimitris @dimitrisl ,

A new version, 1.0.2, built against itk-5.0.0.post1 has been uploaded to PyPI, which should fix your segmentation fault issue.

Please try:

```
python -m pip install --upgrade itk-anisotropicdiffusionlbr
```

and let us know how it goes.

**Comment by dimitrisl** [comment]
Hello @thewtex ,
It seems to work now :) thanks a lot!

**Comment by dimitrisl** [comment]
hello again @thewtex 

it seems that another issue occured. 
In [5]: instance = itk.CoherenceEnhancingDiffusionImageFilter(rescaled_image)                            
Segmentation fault (core dumped)

**Comment by thewtex** [comment]
@dimitrisl could a [SSCCE](http://sscce.org/) be shared?

**Comment by dimitrisl** [comment]
@thewtex 

```
import matplotlib.pyplot as plt
import numpy as np
import itk

image = np.random.randn(1517, 1501).astype("float32")
rescaled_image = (image - np.min(image))/np.ptp(image)
rescaled_image = itk.GetImageViewFromArray(rescaled_image)
instance = itk.CoherenceEnhancingDiffusionImageFilter[itk.Image[itk.F,2]].New(rescaled_image)

instance = itk.GetArrayViewFromImage(instance)
plt.imshow(instance) # essentially it breaks on this point here..but this behaviour is not consistent
plt.show()

```

**Comment by thewtex** [comment]
This

```
instance = itk.CoherenceEnhancingDiffusionImageFilter[itk.Image[itk.F,2]].New(rescaled_image)
```

Needs to be

```
instance = itk.CoherenceEnhancingDiffusionImageFilter[itk.Image[itk.F,2]].New(rescaled_image)
instance.Update()
```

or the filter is not executed, and the output is not populated. Alternatively, use ITK 5 Pythonic syntax, which determines the required type, runs `.Update()` and returns the filter's output:

```
smoothed_image = itk.coherence_enhancing_diffusion_image_filter(rescaled_image)
```

Also, this does not work:

```
instance = itk.GetArrayViewFromImage(instance)
```

because it is generate a *view* on an image instance (i.e. a look into the image's pixel buffer memory), but then it is overwriting the image instance. The view will not be pointing to anything that exists, which will cause a crash. Instead, use:

```
instance = itk.GetArrayFromImage(instance)
```

or the nicer:

```
instance = itk.array_from_image(instance)
```
```

**Comment by dimitrisl** [comment]
> itk.array_from_image(instance)

@thewtex Awesome!! Thank you very much, it really saved me a lot of time.
Thanks again for the fast and helpful answers!
